### ISSUE TITLE
Ship the package supporting AutoMapper 8.1

### ISSUE THREAD

**Issue by she2** [threenine/Threenine.Map#4]
I am just wondering why you are yet to ship the changes you made to the library. If you can, please update the library.

**Comment by garywoodfine** [comment]
It all basically comes down to time and interest.   

it's very difficult to gauge how many people actually use the library.  We get very few issues logged, in fact this is the only issue that  has ever been raised.   

Will try find sometime at some point to do a release.  We have to change the entire CI/CD pipeline because we have moved away from Appveyor and use Teamcity internally now. So we would have to schedule this work too

**Comment by garywoodfine** [comment]
Replaced CI/CD workflow

Updated the package.

New updated package has been deployed to nuget and is available
